"{ Plugins from Vim-Plug
call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdcommenter'
Plug 'itchyny/lightline.vim'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-markdown'

call plug#end()
"}

set nocompatible "Use Vim settings, rather than Vi settings

filetype on
filetype indent on
syntax on
colorscheme Tomorrow-Night

set number "Show line numbers
set hidden "Hide, not close buffers
set history=100 "More in memory for speed increase
set showmatch "Show matching brackets/parenthesis
set showmode "Show current mode
set list "Show trailing charachters
set listchars=tab:│\ ,trail:•,extends:❯,precedes:❮  " ... but only show tabs and trailing whitespace
set backspace=indent,eol,start "Allow backspacing over everything in insert mode
set noshowmode "Remove insert/visual etc from status line, since I use lightline
set laststatus=2

"{ Encoding
set encoding=utf-8
"}

"{ Indenting
set nowrap
set tabstop=2 "I like 2 stops
set shiftwidth=2 "Use spaces for indenting
set expandtab
set smartindent
set autoindent
"}

"{ Searching
set hlsearch "Highlight words when searching
set ignorecase "Ignore cases when searching
set smartcase "Don't ignore case when pattern contains upper case
"}

"Remove trailing whitespace on close
autocmd BufWritePre * :%s/\s\+$//e

"Space as leader
let mapleader="\<Space>"
"Open previous file
nnoremap <Leader><Leader> :e#<CR>
"Reload config
map <leader>s :source ~/.vimrc<CR>
"Toggle NERDTree
nmap <leader>n :NERDTreeToggle<CR>

"{ NerdTree
let g:NERDTreeMapActivateNode='<right>'
let g:NERDTreeShowHidden=0
let g:NERDTreeIgnore=['\.DS_Store', '\~$', '\.swp']
let g:NERDTreeWinSize=30
"}

"{ Git Gutter
let g:gitgutter_sign_column_always=1
"}
