# PATH TO  MY oh-my-zsh CONFIG.
ZSH=$HOME/.oh-my-zsh

# SET CHARMAP
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# HISTORY SETTINGS
HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=4500

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="risto"
ZSH_THEME="robbyrussell"

# LOAD COLORS FOR PS1
#autoload -U colors && colors
#export CLICOLOR=1

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git osx tmux mosh sublime web-search)

source $ZSH/oh-my-zsh.sh

# Universal aliases
alias ipecho="curl ipecho.net/plain; echo"
alias zshconfig="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"
alias caracal="mosh haakool@caracal.stud.ntnu.no"
alias hakloev="mosh hakloev@hakloev.no"
alias shakloev="ssh hakloev@hakloev.no"
alias tmux="TERM=screen-256color-bce tmux"
alias airport="~/git/scripts/airport.sh"

# Editor
EDITOR='vim' 

export M2_HOME=/Users/hakloev/Downloads/apache-maven-3.2.3 
export M2=$M2_HOME/bin
export PATH=$M2:$PATH
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre
export PATH=$JAVA_HOME:$PATH

#Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"
