" Plugins
call plug#begin('~/.vim/plugged')

Plug 'itchyny/lightline.vim'
Plug 'scrooloose/nerdtree'
"Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
"Plug 'junegunn/fzf.vim'
Plug 'junegunn/rainbow_parentheses.vim'
Plug 'w0rp/ale'

" languages
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'

call plug#end()

" General {
set encoding=utf-8              " well, you know
scriptencoding utf-8            " do I need say more?
set clipboard=unnamed           " system clipboard
set nocompatible
syntax enable                   " syntax highlighting
filetype plugin indent on       " depend indent on filetype
set autoread                    " auto load changed files
set nobackup                    " disable backup files
set noswapfile                  " disable swap files
set history=100                 " increase history

" Style
set t_Co=256                    " colors
set background=dark
set number                      " line numbers
set ruler                       " show cursor position
set showcmd                     " show incomplete command
set novisualbell                " drop those stupid flashes
set showmatch                   " show matching brackets

" Tabs, spaces and all that
set nowrap                      " dont wrap long lines
set tabstop=2                   " use two as default
set shiftwidth=2                " spaces for indent
set expandtab                   " use spaces, not tabs! override for filetypes
set autoindent                  " keep indent
set smartindent
set backspace=indent,eol,start  " backspace in insert mode
set list                        " show trailing charachters
set listchars=tab:\|\ ,trail:•,extends:❯,precedes:❮ " ... but only show tabs and trailing whitespace
set laststatus=2                " status line

" Searching
set hlsearch                    " hightlight matches
set ignorecase                  " dont be case sensitive
set smartcase                   " ...but not when pattern has upper case

" Windows
set splitright                  " horizontal splits to the right
set splitbelow                  " vertical splits below
" }

" Mapping {
let mapleader=','

nnoremap <Leader>vv :vsplit $HOME/.vimrc<CR>  " load vimrc
nnoremap <Leader>sv :source $HOME/.vimrc<CR>  " source vimrc
nnoremap <CR> :nohlsearch<CR>                 " clear search on return

" navigation
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-H> <C-W>h
nnoremap <C-L> <C-W>l

nnoremap <Leader>n :NERDTreeToggle<CR>
nnoremap <Leader>w :ALEDetail<CR>
" }

" FileTypes {

  " remove trailing whitespace on save
  autocmd BufWritePre * :%s/\s\+$//e

  augroup filetype_json
    au!
    au BufNewFile,BufRead *.json setf javascript
  augroup END

  augroup filetype_python
    au!
    au FileType python setl sts=4 ts=4 sw=4
  augroup END
" }

" Plugin Configuration {
let g:NERDTreeHighlightCursorline = 0
let g:NERDTreeMouseMode = 3
let g:fzf_layout = { 'down': '~30%' }
let g:lightline = { 'mode_fallback': { 'terminal': 'normal' } }

" Ale
let g:ale_fixers = {
            \   '*': ['remove_trailing_lines', 'trim_whitespace'],
            \   'javascript': ['eslint'],
            \   'elm': ['format'],
            \}
let g:ale_fix_on_save = 1
let g:ale_lint_on_save = 1
let g:ale_completion_enabled = 0
let g:ale_sign_column_always = 1
" }
