#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export EDITOR="vim"
export HISTSIZE=1000000 # Set history size
export SAVEHIST=1000000 # Save history after logout
export HISTFILE="$HOME/.zsh_history"

# PATH
export PATH="/usr/local/opt/curl/bin:$PATH"

# Maven
export M2_REPO="$HOME/.m2/repository"

# FZF
export FZF_DEFAULT_COMMAND="fd --type f --strip-cwd-prefix"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"

# macOS exports
if [[ "$OSTYPE" == darwin* ]] then
  export JAVA_HOME=$(/usr/libexec/java_home) # Specify version with: $(/usr/libexec/java_home -v 1.8.0_265)
  export PATH=${JAVA_HOME}/bin:$PATH
  export GPG_TTY=$(tty) # For gpg on macOS
fi

# Export Finn specific exports if the file exists
if [ -f $HOME/.finnrc ]; then
  source ~/.finnrc
fi

if [ -d $HOME/.rm ]; then
  export PATH="$HOME/.rm:$PATH"
fi
