# History
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt SHARE_HISTORY

export HISTSIZE=1000000 # Set history size
export SAVEHIST=$HISTSIZE # Save history after logout
export HISTFILE=$HOME/.zsh_history
export HISTORY_IGNORE="(clear|history|exit|ls|gs|gd|cd|pwd)"

# General
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export EDITOR="vim"
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8,underline"

# FZF
export FZF_DEFAULT_COMMAND="fd --type f --strip-cwd-prefix"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"

# macOS exports
if [[ $(uname) == Darwin ]] then
  export JAVA_HOME=$(/usr/libexec/java_home) # Specify version with: $(/usr/libexec/java_home -v 1.8.0_265)
  export PATH=$JAVA_HOME/bin:$PATH
fi

# Maven
export M2_REPO="$HOME/.m2/repository"

# NVM
export NVM_DIR="$HOME/.nvm"
  [ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && \. "$(brew --prefix)/opt/nvm/nvm.sh" # This loads nvm

# GCP
source "$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
source "$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"

# Project specific exports
if [ -d $HOME/.rm ]; then
  export PATH=$HOME/.rm:$PATH
fi
