#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export EDITOR="vim"
export HISTSIZE=1000000 # Set history size
export SAVEHIST=1000000 # Save history after logout
export HISTFILE="$HOME/.zsh_history"

export GOPATH="$HOME/.go"
export GOBIN=$GOPATH/bin
export PATH=$GOBIN:$PATH

export PATH="/usr/local/opt/curl/bin:$PATH"


export M2_REPO="$HOME/.m2/repository"

# macOS exports
if [[ "$OSTYPE" == darwin* ]] then
  export JAVA_HOME=`/usr/libexec/java_home`
  export GPG_TTY=$(tty) # For gpg on macOS
fi

# Export NSB specific exports if the file exists
if [ -f ~/.nsbrc ]; then
  source ~/.nsbrc
fi
