#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs..
alias ed25519key='ssh-keygen -t ed25519 -o -a 100'

alias mci='mvn clean install'
alias msb='mvn spring-boot:run'
alias mrpr='mvn release:prepare'
alias mrpe='mvn release:perform'

alias st="open -a Sublime\ Text.app $1"

alias weather='curl http://wttr.in/oslo'

alias cleanxcode="rm -rf $HOME/Library/Developer/Xcode/DerivedData/*"

# Personal shell functions
if [[ "$OSTYPE" == darwin* ]] then
  function sethostname () {
    sudo scutil --set ComputerName $1
    sudo scutil --set LocalHostName $1
    sudo scutil --set HostName $1
  }
fi

# FZF
fzf_git_log() {
    local commits=$(
      git l --color=always "$@" |
        fzf --ansi --no-sort --height 100% \
            --preview "git show --color=always {2}"
      )
    if [ -n "$commits" ]; then
        local hashes=$(printf "$commits" | cut -d' ' -f2 | tr '\n' ' ')
        git show $hashes
    fi
}

fzf_git_add() {
    local files=$(git ls-files --modified | fzf --ansi)
    if [ -n "$files" ]; then
        git add --verbose $files
    fi
}

alias glo='fzf_git_log'
alias gaa='fzf_git_add'
alias gl='git l'
alias ga='git add'
alias gs='git s'
alias gd='git d'
alias gc='git checkout'
alias gf='git fetch'
alias gpl='git pull'
alias gpu='git push'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# added by travis gem
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh
