# Antidote Plugin Manager
source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
antidote load

# Brew
BREW_REQUIREMENTS_DIR=$HOME/git/internal/dotfiles/requirements

brew_update() {
  (cd $BREW_REQUIREMENTS_DIR && brew bundle install) # temporary move to './requirements' and run 'brew bundle'
}

brew_cleanup() {
  (cd $BREW_REQUIREMENTS_DIR && brew bundle cleanup $1)
}

alias brew_edit="vim $BREW_REQUIREMENTS_DIR/Brewfile"

# Other
restart_bluetooth() {
  sudo pkill bluetoothd
}

serve() {
  ngrok ${1:-http} ${2:-3000}
}

# Alias
alias dotfiles="cd $HOME/git/internal/dotfiles"

alias cleanxcode="rm -rf $HOME/Library/Developer/Xcode/DerivedData/*"
alias cleannext="rm -rf $PWD/.next/cache"

alias cat='bat'
alias ls='eza' #alias ls='ls -G'
alias mux='tmuxinator'

alias gl='git l'
alias ga='git add'
alias gs='git status -s'
alias gd='git diff'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gc='git commit'
alias gcm='git commit -m'
alias gca='git commit --amend'
alias gf='git fetch'
alias gm='git merge'
alias gp='git push'
alias gpl='git pull'

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# NVM
export NVM_DIR="$HOME/.nvm"
  [ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && \. "$(brew --prefix)/opt/nvm/nvm.sh" # This loads nvm

eval "$(direnv hook zsh)"
eval "$(starship init zsh)"
