#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Set to false to avoid auto-completion bug that eats lines in the shell
export COMPLETION_WAITING_DOTS="false"

# Customize to your needs..
alias ed25519key='ssh-keygen -t ed25519 -o -a 100'

alias mcinst='mvn clean install'
alias msboot='mvn spring-boot:run'
alias mrpre='mvn release:prepare'
alias mrper='mvn release:perform'

alias st="open -a Sublime\ Text.app $1"

alias weather='curl http://wttr.in/oslo'
