cask_args appdir: '/Applications'
tap 'homebrew/services'
cask 'java' unless system "/usr/libexec/java_home --failfast" # Must be added early on

cask 'iterm2'
cask 'visual-studio-code'
cask 'intellij-idea' # 'intellij-idea-ce' for community-edition
cask 'docker'
cask 'rectangle'
cask 'kap'

cask 'google-chrome'
cask 'firefox'
cask 'postman'

cask 'slack'
cask 'discord'
cask 'spotify'

cask '1password'

brew 'zsh'
brew 'wget'
brew 'git'
brew 'openssl'
brew 'nodejs'
brew 'sqlite'
brew 'python3'
brew 'tree'

brew 'swiftlint'
