cask_args appdir: '~/Applications'
tap 'homebrew/services'
tap 'homebrew/cask-fonts'

brew 'mas'

cask 'alacritty'
cask 'iterm2'

brew 'zsh'
brew 'starship'
brew 'antidote'
brew 'tmux'
brew 'tmuxinator'
brew 'git'
brew 'wget'
brew 'openssl'
brew 'jq'
brew 'grep'
brew 'eza'
brew 'fd'
brew 'bat'
brew 'fzf'
brew 'tree'
brew 'tree-sitter'

brew 'openjdk@17'
brew 'python3'
brew 'pipenv'
brew 'nodejs'
brew 'nvm'
brew 'maven'
brew 'sqlite'
brew 'go'
brew 'go-task'

cask '1password'
mas '1Password for Safari', id: 1569813296
mas 'Tailscale', id: 1475387142

cask 'intellij-idea'
cask 'visual-studio-code'
cask 'raycast'
cask 'ngrok'
cask 'rectangle'
cask 'kap'
brew 'gifski'

cask 'google-chrome'
cask 'firefox'
cask 'vivaldi'
cask 'postman'
cask 'obsidian'
cask 'remarkable'
cask 'slack'
cask 'discord'
cask 'sonos'

brew 'docker'
brew 'docker-compose'
brew 'colima' # Replaces Docker Desktop

brew 'direnv'

cask 'google-cloud-sdk'

cask 'font-jetbrains-mono-nerd-font'

brew 'tfenv' # Terraform environment
brew 'terraform-ls'
brew 'tflint'
